version: '3.8'

services:
  backend:
    build: ./backend
    container_name: fintrack-backend
    ports:
      - "8085:8080"
    volumes:
      - backend-data:/app/data
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: fintrack-frontend
    ports:
      - "5500:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend-data:
